"""Public API for Local Semantic Overlay."""

from .audit import audit_lso
from .cold_start import (
    audit_seed_routes,
    begin_seed_map,
    commit_seed_route,
    expand_cluster_evidence,
    finish_seed_map,
    list_terrain_clusters,
    preview_seed_routes,
    prune_seed_routes,
    seed_lso_routes,
    seed_map_report,
    survey_scope,
)
from .maintenance import maintenance_tick
from .runtime import (
    audit_runtime,
    apply_update_plan,
    begin_file_task,
    expand_route,
    finish_local_file_task,
    list_route_cards,
    lso_summary,
    recall_hits,
    recall_routes,
    record_correction,
    run_file_query,
    system_overview,
    update_route_tags,
)
from .search_substrate import (
    ensure_search_ready,
    last_search_diagnostic,
    resolve_es_exe,
    search_files_detailed,
    search_files_paths,
    search_files_rows,
)

__all__ = [
    "apply_update_plan",
    "audit_lso",
    "audit_runtime",
    "audit_seed_routes",
    "begin_seed_map",
    "begin_file_task",
    "commit_seed_route",
    "ensure_search_ready",
    "expand_cluster_evidence",
    "expand_route",
    "finish_seed_map",
    "finish_local_file_task",
    "last_search_diagnostic",
    "list_terrain_clusters",
    "list_route_cards",
    "lso_summary",
    "maintenance_tick",
    "preview_seed_routes",
    "prune_seed_routes",
    "recall_hits",
    "recall_routes",
    "record_correction",
    "resolve_es_exe",
    "run_file_query",
    "search_files_detailed",
    "search_files_paths",
    "search_files_rows",
    "seed_lso_routes",
    "seed_map_report",
    "system_overview",
    "survey_scope",
    "update_route_tags",
]
