"""上汽MG销售接待SOP - 全量规则，场景门控激活（首版短超时便于联调）"""

# 留资：进入 / 强跳 / 回退 / must 命中共用
CONTACT_STAGE_KWS = ["留个", "联系方式", "电话", "手机号", "加个微信", "方便留"]

SOP_RULES = {
    "stages": [
        {
            "id": "greeting",
            "name": "迎接准备",
            "hint_next": True,
            "enter_keywords": ["你好", "欢迎", "光临", "看车", "进来", "您好"],
            "enter_strong": [],
            "reenter_keywords": [],
            "must": [
                {
                    "id": "confirm_appointment",
                    "desc": "确认预约",
                    "scene": "greeting",
                    "keywords": ["预约", "专属销售", "之前联系", "电话邀约", "网上预约", "提前约"],
                    "alert": "请确认有无预约。",
                    "audio_id": "confirm_appointment",
                    "timeout_sec": 3,
                    "activate": {"mode": "after_stage_enter"},
                },
                {
                    "id": "confirm_intent",
                    "desc": "确认意向车型",
                    "scene": "greeting",
                    "keywords": ["哪款", "看什么车", "意向", "想看", "了解哪", "哪个车型", "感兴趣的", "MG4", "MG7", "ES5"],
                    "alert": "请确认预约或意向车。",
                    "audio_id": "confirm_intent",
                    "timeout_sec": 6,
                    "activate": {"mode": "after_stage_enter"},
                },
            ],
            "forbidden": [],
        },
        {
            "id": "self_intro",
            "name": "需求分析",
            "hint_next": True,
            "enter_keywords": ["我是", "我叫", "销售顾问", "自我介绍", "我来为您", "需求", "要求", "什么"],
            "enter_strong": [],
            "reenter_keywords": ["再想想", "再考虑"],
            "must": [
                {
                    "id": "self_intro",
                    "desc": "自我介绍",
                    "scene": "needs",
                    "keywords": ["我叫", "我是", "我姓", "销售顾问", "我的名字"],
                    "alert": "记得自我介绍。",
                    "audio_id": "self_intro",
                    "timeout_sec": 3,
                    "activate": {"mode": "after_stage_enter"},
                },
                {
                    "id": "invite_car",
                    "desc": "邀请上车体验",
                    "scene": "needs",
                    "keywords": ["坐进去", "上车感受", "进车里", "体验一下", "坐到驾驶位", "打开车门", "坐进来", "亲自感受", "上车看看"],
                    "alert": "邀请客户上车体验。",
                    "audio_id": "invite_car",
                    "timeout_sec": 6,
                    "activate": {"mode": "on_behavior", "min_sec": 2},
                },
                {
                    "id": "ask_experience",
                    "desc": "探寻用车经验",
                    "scene": "needs",
                    "keywords": ["之前开", "现在开", "第几辆", "对比过", "用车经验", "开过什么", "换车", "增购", "了解过", "新能源接受"],
                    "alert": "探寻一下用车经验。",
                    "audio_id": "ask_experience",
                    "timeout_sec": 9,
                    "activate": {"mode": "on_behavior", "min_sec": 2},
                },
            ],
            "forbidden": [],
        },
        {
            "id": "hint_test_drive",
            "name": "产品介绍",
            "hint_next": True,
            "enter_keywords": [
                "为您介绍", "给您介绍", "给您讲讲", "这款车", "配置", "亮点", "卖点",
                "外观", "内饰", "底座", "空间", "性能", "车型",
            ],
            "enter_strong": ["最大的优势", "车型版本"],
            "reenter_keywords": ["再介绍", "再说说", "再给您介绍", "再看看"],
            "must": [
                {
                    "id": "hint_test_drive",
                    "desc": "铺垫试驾",
                    "scene": "product",
                    "keywords": ["试驾", "开一圈", "体验动力", "去试试", "开出去感受"],
                    "trigger": ["多少钱", "价格", "优惠", "落地", "分期", "月供", "动力怎么样", "加速", "百公里", "续航多少", "能跑多远"],
                    "alert": "顺势铺垫试驾。",
                    "audio_id": "hint_test_drive",
                    "timeout_sec": 3,
                    "activate": {"mode": "on_trigger"},
                },
                {
                    "id": "invite_test_drive",
                    "desc": "邀约试驾",
                    "scene": "product",
                    "keywords": ["试驾", "开一圈", "体验一下动力", "去试试", "开出去", "自己开", "排程", "是否有时间", "安排试驾"],
                    "alert": "别忘了邀约试驾。",
                    "audio_id": "invite_test_drive",
                    "timeout_sec": 3,
                    "activate": {"mode": "on_end_view", "keywords": ["去坐坐", "算个价格", "先回去", "回去考虑", "回去聊聊"]},
                },
            ],
            "forbidden": [],
        },
        {
            "id": "get_contact",
            "name": "留资开口",
            "hint_next": True,
            "enter_keywords": list(CONTACT_STAGE_KWS),
            "enter_strong": list(CONTACT_STAGE_KWS),
            "reenter_keywords": list(CONTACT_STAGE_KWS),
            "must": [
                {
                    "id": "get_phone",
                    "desc": "留电话",
                    "scene": "contact",
                    "keywords": list(CONTACT_STAGE_KWS),
                    "alert": "请争取留下电话。",
                    "audio_id": "get_phone",
                    "timeout_sec": 3,
                    "activate": {"mode": "after_stage_enter"},
                },
                {
                    "id": "try_wechat",
                    "desc": "加微信",
                    "scene": "contact",
                    "keywords": list(CONTACT_STAGE_KWS) + ["微信", "扫一下", "朋友圈", "企业微信"],
                    "trigger": ["不用了", "不需要", "不留了", "不方便", "下次吧", "再说吧", "不加"],
                    "alert": "试着加个微信。",
                    "audio_id": "try_wechat",
                    "timeout_sec": 3,
                    "activate": {"mode": "on_trigger"},
                },
            ],
            "forbidden": [],
        },
        {
            "id": "drive_route",
            "name": "准备试驾",
            "hint_next": True,
            "enter_keywords": ["去试驾", "备车", "出发前"],
            "enter_strong": ["准备试驾", "安排试驾", "试驾路线", "签署协议", "试驾协议", "试驾宝", "试驾车准备", "开始试驾前"],
            "reenter_keywords": [],
            "must": [
                {
                    "id": "drive_route",
                    "desc": "介绍试驾路线",
                    "scene": "pre_drive",
                    "keywords": ["路线", "路况", "红绿灯", "高架", "环路", "公里", "大概多久", "走哪条路"],
                    "alert": "简单说明试驾路线。",
                    "audio_id": "drive_route",
                    "timeout_sec": 3,
                    "activate": {"mode": "on_scene_enter", "keywords": ["去开一圈", "拿钥匙", "试驾车", "我们出去"]},
                },
                {
                    "id": "sign_agreement",
                    "desc": "签署协议",
                    "scene": "pre_drive",
                    "keywords": ["签协议", "扫码", "试驾协议", "签字", "试驾宝", "电子协议"],
                    "alert": "务必签试驾协议！",
                    "audio_id": "sign_agreement",
                    "timeout_sec": 6,
                    "activate": {"mode": "on_scene_enter", "keywords": ["系好安全带", "启动", "挂挡", "出发"]},
                },
                {
                    "id": "phone_prepare",
                    "desc": "手机备车",
                    "scene": "pre_drive",
                    "keywords": ["一键备车", "近场移车", "无感解锁", "安全带", "远程解锁", "移车"],
                    "alert": "演示手机备车和安全带。",
                    "audio_id": "phone_prepare",
                    "timeout_sec": 9,
                    "activate": {"mode": "on_scene_enter", "keywords": ["车在外面", "我们出去", "去试驾车"]},
                },
                {
                    "id": "phone_connect",
                    "desc": "手机互联",
                    "scene": "pre_drive",
                    "keywords": ["互联", "投屏", "CarPlay", "抖音", "B站", "摇一摇", "连接手机"],
                    "alert": "演示手机互联投屏。",
                    "audio_id": "phone_connect",
                    "timeout_sec": 12,
                    "activate": {"mode": "on_scene_enter", "keywords": ["系好安全带", "起步", "出发"]},
                },
            ],
            "forbidden": [],
        },
        {
            "id": "adjust_seat",
            "name": "试驾",
            "hint_next": True,
            "enter_keywords": ["启动车辆", "驾驶模式", "踩油门", "踩电门"],
            "enter_strong": ["运动模式", "开始试驾"],
            "reenter_keywords": [],
            "must": [
                {
                    "id": "safe_stop",
                    "desc": "安全停车下车",
                    "scene": "drive",
                    "keywords": ["安全位置", "注意后方", "靠边停", "打开双闪", "注意安全"],
                    "trigger": ["您来开", "换您开", "你来试试", "换手", "找个地方停", "换您试试"],
                    "alert": "提醒安全停车下车。",
                    "audio_id": "safe_stop",
                    "timeout_sec": 3,
                    "activate": {"mode": "on_trigger"},
                },
                {
                    "id": "adjust_seat",
                    "desc": "调座椅后视镜",
                    "scene": "drive",
                    "keywords": ["调座椅", "后视镜", "调整座位", "方向盘高度", "坐姿", "安全带"],
                    "trigger": ["您来开", "换你开", "你来试试", "换手", "我来开", "让我开"],
                    "alert": "提醒调座椅后视镜。",
                    "audio_id": "adjust_seat",
                    "timeout_sec": 6,
                    "activate": {"mode": "on_trigger"},
                },
                {
                    "id": "energy_recovery",
                    "desc": "动能回收",
                    "scene": "drive",
                    "keywords": ["动能回收", "回收", "单踏板", "制动能量", "滑行充电", "拖拽感"],
                    "alert": "结合场景讲动能回收。",
                    "audio_id": "energy_recovery",
                    "timeout_sec": 9,
                    "activate": {"mode": "after_drive_enter"},
                },
                {
                    "id": "guide_experience",
                    "desc": "引导体验",
                    "scene": "drive",
                    "keywords": ["语音助手", "加速感受", "试试语音", "深踩", "地板油", "NOA", "辅助驾驶", "你踩一脚", "体验一下加速", "踩电门"],
                    "alert": "引导客户体验加速。",
                    "audio_id": "guide_experience",
                    "timeout_sec": 12,
                    "activate": {"mode": "after_drive_enter"},
                },
                {
                    "id": "collect_feedback",
                    "desc": "收集反馈",
                    "scene": "drive",
                    "keywords": ["感觉怎么样", "体验如何", "还满意吗", "觉得怎样", "感受如何", "还行吗", "好开吗"],
                    "alert": "问问客户驾驶感受。",
                    "audio_id": "collect_feedback",
                    "timeout_sec": 15,
                    "activate": {"mode": "after_drive_enter"},
                },
            ],
            "forbidden": [],
        },
        {
            "id": "auto_park",
            "name": "结束试驾",
            "hint_next": True,
            "enter_keywords": ["回到店", "停好了", "试驾结束", "回来了"],
            "enter_strong": ["自动泊车", "体验自动泊车", "还有什么想了解"],
            "reenter_keywords": [],
            "must": [
                {
                    "id": "auto_park",
                    "desc": "自动泊车",
                    "scene": "post_drive",
                    "keywords": ["自动泊车", "泊车", "自动停车", "泊车辅助", "一键泊车", "离车泊入"],
                    "trigger": ["回去吧", "返程", "回店", "往回走", "掉头", "回去了", "快到店", "准备停车"],
                    "alert": "邀请体验自动泊车。",
                    "audio_id": "auto_park",
                    "timeout_sec": 3,
                    "activate": {"mode": "on_trigger"},
                },
                {
                    "id": "drive_review",
                    "desc": "功能回顾",
                    "scene": "post_drive",
                    "keywords": ["总结", "回顾", "刚才体验", "今天试了", "NOA", "语音控制", "整体感觉"],
                    "alert": "快速总结试驾体验。",
                    "audio_id": "drive_review",
                    "timeout_sec": 6,
                    "activate": {"mode": "on_scene_enter", "keywords": ["回店了", "下车吧", "试驾结束", "停好了", "到了"]},
                },
                {
                    "id": "invite_in_store",
                    "desc": "邀请进店",
                    "scene": "post_drive",
                    "keywords": ["进店", "坐坐", "喝口水", "喝杯茶", "店里聊", "算算账", "配置方案", "现车", "饮品"],
                    "trigger": ["先回去了", "今天就到这", "改天再来", "走了", "下次", "回去考虑"],
                    "alert": "务必邀请客户进店。",
                    "audio_id": "invite_in_store",
                    "timeout_sec": 3,
                    "activate": {"mode": "on_trigger"},
                },
            ],
            "forbidden": [],
        },
    ],
    "insert_rules": [
        {
            "id": "get_phone_leave",
            "desc": "离店留电话",
            "scene": "contact",
            "keywords": list(CONTACT_STAGE_KWS) + ["留个电话"],
            "alert": "请争取留下电话。",
            "audio_id": "get_phone",
            "timeout_sec": 3,
            "activate": {
                "mode": "on_leave_intent",
                "keywords": ["先走了", "下次再来", "先回去", "慢走", "回去考虑"],
            },
        },
        {
            "id": "invite_test_drive_retry",
            "desc": "二次邀约试驾",
            "scene": "product",
            "keywords": ["试驾", "开一圈", "安排试驾", "体验一下动力"],
            "alert": "别忘了邀约试驾。",
            "audio_id": "invite_test_drive",
            "timeout_sec": 3,
            "activate": {"mode": "on_second_invite"},
        },
    ],
}
